### ISSUE TITLE
 TypeError: now() got an unexpected keyword argument 'settings'

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-publish-vercel#31]
https://github.com/simonw/til/runs/1618711889?check_suite_focus=true

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/datasette", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: now() got an unexpected keyword argument 'settings'
```

**Comment by simonw** [comment]
Weird, I can't replicate this locally.

**Comment by simonw** [comment]
Aha! The problem is in the `datasette publish now` alias: https://github.com/simonw/datasette-publish-vercel/blob/4884ed4ed2d4ede2e80d76d82d8693ddc5e5bba4/datasette_publish_vercel/__init__.py#L321-L376
