### ISSUE TITLE
Ensure ds.invoke_startup() runs on startup

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-publish-vercel#54]
This is needed by plugins that use the `startup()` plugin hook.

> It crashed:
> `[ERROR] AttributeError: 'Datasette' object has no attribute '_hashed_url_databases'Traceback (most recent call last):  File "/var/task/vc__handler__python.py", line 293, in vc_handler    response = asgi_cycle(__vc_module.app, body)  File "/var/task/vc__handler__python.py", line 204, in __call__    loop.run_until_complete(asgi_task)  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete    return future.result()  File "/var/task/datasette_hashed_urls/__init__.py", line 38, in hashed_urls    if db_name in datasette._hashed_url_databases:`
> Presumably because `datasette-publish-vercel` doesn't arrange for the `startup()` hooks to be called!

https://github.com/simonw/datasette-publish-vercel/blob/b07f62d034e7cc62ba56309712ddb5c4349a38d7/datasette_publish_vercel/__init__.py#L39-L47

_Originally posted by @simonw in https://github.com/simonw/datasette-hashed-urls/issues/2#issuecomment-1068541831_

**Comment by simonw** [comment]
I tested this here and it works now:
- https://github.com/simonw/datasette-hashed-urls/issues/4#issuecomment-1068548127
