### ISSUE TITLE
RuntimeError('There is no current event loop in thread %r.')

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-publish-vercel#58]
https://til.simonwillison.net/ site is down at the moment:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/9599/180585291-b3565178-53c6-45b1-9ff3-78bfe2c9033b.png">

Logs at https://vercel.com/datasette/simon-til/9SYmpgw4ExnTbRLnsevw5zXXTRgb/functions show:

`[ERROR] RuntimeError: There is no current event loop in thread 'MainThread'.Traceback (most recent call last):  File "/var/task/vc__handler__python.py", line 453, in vc_handler    lifespan = Lifespan(__vc_module.app)  File "/var/task/vc__handler__python.py", line 308, in __init__    self.loop = get_event_loop()  File "/var/task/vc__handler__python.py", line 184, in get_event_loop    return asyncio.get_event_loop()  File "/var/lang/lib/python3.9/asyncio/events.py", line 642, in get_event_loop    raise RuntimeError('There is no current event loop in thread %r.'`

**Comment by simonw** [comment]
I think this is because of changes to Vercel's Python support.

I happened to have a copy of the working `vc__handler__python.py` from this morning. I generated a new copy using `vercel build` and here's the diff:

https://gist.github.com/simonw/8521ba3385279fde4a9878f2ad8d150a/revisions

That diff does indeed show newly added code that calls `asyncio.get_running_loop()`:

```python
         def get_event_loop():
            try:
                return asyncio.get_running_loop()
            except:
                if sys.version_info < (3, 10):
                    return asyncio.get_event_loop()
                else:
                    return asyncio.get_event_loop_policy().get_event_loop()
```

**Comment by simonw** [comment]
It looks to me like this commit introduced the bug: https://github.com/vercel/vercel/commit/66c8544e8fb7b8eb77106d8b428ef6736b9ecb45

It was supposed to fix an issue in Python 3.10. I'm still running Python 3.9 here - so maybe upgrading to Python 3.10 will work around this issue.

**Comment by simonw** [comment]
The docs at https://vercel.com/docs/runtimes#official-runtimes/python/python-version suggest that you can't run anything other than Python 3.6 or 3.9.

**Comment by simonw** [comment]
From the PR at https://github.com/vercel/vercel/pull/8045/files it looks like I might be able to use a `Pipfile` with `python_version = "3.10"` in it as a workaround.

**Comment by simonw** [comment]
I tried a manual deploy using the output from `--generate-dir`

I had to delete `requirements.txt` - having both that and `Pipfile` continued to deploy Python 3.9.

This `Pipfile`:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
datasette = '*'

[requires]
python_version = "3.10"
```
Seems to have worked in that I'm not getting the old error - I think it deployed Python 3.10 though I've not confirmed it yet, because now I get this error instead:

`[ERROR] Runtime.ImportModuleError: Unable to import module 'vc__handler__python': No module named 'datasette'`

**Comment by simonw** [comment]
Alternative workaround, maybe try pinning https://www.npmjs.com/package/@vercel/python to `3.0.7`?

**Comment by simonw** [comment]
Here's how to pin that: https://github.com/vercel-support/flask-test/blob/e8b6f669787c5a7a1343c1e78660ea26407c2a0c/vercel.json#L6

**Comment by simonw** [comment]
Yes, this seems to fix it:

            "use": "@vercel/python@3.0.7"
