### ISSUE TITLE
--setting allow_download 0 causes a 500 error

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-publish-vercel#61]
```
[ERROR] NameError: name 'false' is not defined
Traceback (most recent call last):
File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/var/task/vc__handler__python.py", line 12, in <module>
    __vc_spec.loader.exec_module(__vc_module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "./index.py", line 27, in <module>
    settings={"allow_download": false}
Unknown application error occurred
```

_Originally posted by @simonw in https://github.com/simonw/sfms-history/issues/25#issuecomment-1226030255_

**Comment by simonw** [comment]
Here's the problem: https://github.com/simonw/datasette-publish-vercel/blob/57aed0fde35bd48094532074b189b63bf3f3ccd3/datasette_publish_vercel/__init__.py#L260-L268

Using `json.dumps()` to produce Python source code means boolean false becomes `false` and not `False`.

**Comment by simonw** [comment]
I'm going to do the cheapest fix: `false = False` and `true = True`.

**Comment by simonw** [comment]
Tested here: https://test-allow-download-0-gau7rnspn-simonw.vercel.app/fixtures
